pool:
  vmImage: 'vs2017-win2016'

strategy:
  maxParallel: 10

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.3'
  displayName: 'Install Node.js'
- script: |
    yarn install --ignore-engines
  displayName: 'Install dependencies'
- script: |
    yarn run test
  displayName: 'Run tests'
- script: |
    npm install -g node-gyp && node-gyp configure && node-gyp build
  displayName: 'Build binary'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'nsfw-win.node'
    targetPath: 'build/Release/nsfw.node'
- script: |
    npm install -g gh-release-upload
  displayName: 'Install uploader'
- script: |
    gh-release-upload build/Release/nsfw.node
  displayName: 'Upload binary'
  env:
    GITHUB_TOKEN: $(github.token)

trigger:
  tags:
    include:
    - '*'
  branches:
    exclude:
    - '*'
